# Generated by Django 2.1.13 on 2019-11-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
